# syntax=docker/dockerfile:1
ARG NODE_IMAGE=node:24-bookworm-slim
FROM ${NODE_IMAGE} AS build
WORKDIR /app
COPY package.json package-lock.json ./
COPY vendor ./vendor
RUN --mount=type=secret,id=proxy_ca \
    if [ -f /run/secrets/proxy_ca ]; then export NODE_EXTRA_CA_CERTS=/run/secrets/proxy_ca; fi; \
    npm ci --strict-ssl=true --no-audit --no-fund
COPY . .
ARG VITE_API_BASE_URL=/
ARG VITE_DEVNET_METADATA_ORIGIN=https://metadata.funded.vip
ARG VITE_SOLANA_CLUSTER=devnet
ARG VITE_EXPLORE_CLUSTER=devnet
ARG VITE_ALLOW_MAINNET=false
ARG VITE_JACKPOT_ENABLED=false
ARG VITE_DEV_MODE=false
ARG VITE_DEV_AUTOCONNECT=false
ARG VITE_DEV_WALLET_ROLE=creator
ARG VITE_FUNDED_FEE_ROUTER_PROGRAM_ID
ARG VITE_FUNDED_TRADE_FEE_OWNER
ARG VITE_FUNDED_TOKEN_MINT
ARG VITE_FUNDED_SWAP_POOL
ARG VITE_FUNDED_BOOST_BURN_AMOUNT=25000
ARG VITE_FUNDED_PRO_BURN_AMOUNT=100000
ARG VITE_FUNDED_PREMIER_BURN_AMOUNT=250000
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_DEVNET_METADATA_ORIGIN=$VITE_DEVNET_METADATA_ORIGIN \
    VITE_SOLANA_CLUSTER=$VITE_SOLANA_CLUSTER \
    VITE_EXPLORE_CLUSTER=$VITE_EXPLORE_CLUSTER \
    VITE_ALLOW_MAINNET=$VITE_ALLOW_MAINNET \
    VITE_JACKPOT_ENABLED=$VITE_JACKPOT_ENABLED \
    VITE_DEV_MODE=$VITE_DEV_MODE \
    VITE_DEV_AUTOCONNECT=$VITE_DEV_AUTOCONNECT \
    VITE_DEV_WALLET_ROLE=$VITE_DEV_WALLET_ROLE \
    VITE_FUNDED_FEE_ROUTER_PROGRAM_ID=$VITE_FUNDED_FEE_ROUTER_PROGRAM_ID \
    VITE_FUNDED_TRADE_FEE_OWNER=$VITE_FUNDED_TRADE_FEE_OWNER \
    VITE_FUNDED_TOKEN_MINT=$VITE_FUNDED_TOKEN_MINT \
    VITE_FUNDED_SWAP_POOL=$VITE_FUNDED_SWAP_POOL \
    VITE_FUNDED_BOOST_BURN_AMOUNT=$VITE_FUNDED_BOOST_BURN_AMOUNT \
    VITE_FUNDED_PRO_BURN_AMOUNT=$VITE_FUNDED_PRO_BURN_AMOUNT \
    VITE_FUNDED_PREMIER_BURN_AMOUNT=$VITE_FUNDED_PREMIER_BURN_AMOUNT
RUN if [ "$VITE_SOLANA_CLUSTER" = "devnet" ] && [ -z "$VITE_API_BASE_URL" ]; then \
      echo "VITE_API_BASE_URL is required for the Devnet browser build" >&2; exit 1; \
    fi && npm run build && npm prune --omit=dev --ignore-scripts --offline --no-audit --no-fund

FROM ${NODE_IMAGE}
ARG VITE_DEVNET_METADATA_ORIGIN=https://metadata.funded.vip
ENV DEVNET_METADATA_ORIGIN=$VITE_DEVNET_METADATA_ORIGIN
ARG RENDER_GIT_COMMIT
ARG FUNDED_SOURCE_REVISION=${RENDER_GIT_COMMIT:-local-development}
LABEL org.opencontainers.image.source="https://github.com/roger-morrision/funded.app" \
      org.opencontainers.image.revision=$FUNDED_SOURCE_REVISION
ENV FUNDED_BUILD_ID=$FUNDED_SOURCE_REVISION
ENV NODE_ENV=production HOST=0.0.0.0 PORT=8787
WORKDIR /app
COPY --from=build /app /app
RUN chmod -R a+rX /app && mkdir -p /app/data && chown node:node /app/data
USER node
EXPOSE 8787
CMD ["node", "server/index.mjs"]
