FROM node:24-bookworm-slim AS build
WORKDIR /app
COPY package.json package-lock.json ./
COPY vendor ./vendor
RUN npm ci
COPY . .
ARG VITE_API_BASE_URL=/
ARG VITE_SOLANA_CLUSTER=devnet
ARG VITE_EXPLORE_CLUSTER=devnet
ARG VITE_ALLOW_MAINNET=false
ARG VITE_DEV_MODE=false
ARG VITE_DEV_AUTOCONNECT=false
ARG VITE_DEV_WALLET_ROLE=creator
ARG VITE_FUNDED_FEE_ROUTER_PROGRAM_ID
ARG VITE_FUNDED_TRADE_FEE_OWNER
ARG VITE_FUNDED_TOKEN_MINT
ARG VITE_FUNDED_SWAP_POOL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_SOLANA_CLUSTER=$VITE_SOLANA_CLUSTER \
    VITE_EXPLORE_CLUSTER=$VITE_EXPLORE_CLUSTER \
    VITE_ALLOW_MAINNET=$VITE_ALLOW_MAINNET \
    VITE_DEV_MODE=$VITE_DEV_MODE \
    VITE_DEV_AUTOCONNECT=$VITE_DEV_AUTOCONNECT \
    VITE_DEV_WALLET_ROLE=$VITE_DEV_WALLET_ROLE \
    VITE_FUNDED_FEE_ROUTER_PROGRAM_ID=$VITE_FUNDED_FEE_ROUTER_PROGRAM_ID \
    VITE_FUNDED_TRADE_FEE_OWNER=$VITE_FUNDED_TRADE_FEE_OWNER \
    VITE_FUNDED_TOKEN_MINT=$VITE_FUNDED_TOKEN_MINT \
    VITE_FUNDED_SWAP_POOL=$VITE_FUNDED_SWAP_POOL
RUN if [ "$VITE_SOLANA_CLUSTER" = "devnet" ] && [ -z "$VITE_API_BASE_URL" ]; then \
      echo "VITE_API_BASE_URL is required for the Devnet browser build" >&2; exit 1; \
    fi && npm run build && npm prune --omit=dev

FROM node:24-bookworm-slim
ENV NODE_ENV=production HOST=0.0.0.0 PORT=8787
WORKDIR /app
COPY --from=build /app /app
USER node
EXPOSE 8787
CMD ["node", "server/index.mjs"]
