[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
funded_fee_router = "2tRrwGFzRCDmrVY7U6dny4Ea1RqVm7cSrCYFULmK7tik"

[programs.devnet]
funded_fee_router = "2tRrwGFzRCDmrVY7U6dny4Ea1RqVm7cSrCYFULmK7tik"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
