import { createConnectionsController } from './controllers/connections.js';
import { createLaunchPolicyController } from './controllers/launch-policy.js';
import { createReferralsController } from './controllers/referrals.js';
import { createShareConsentController } from './controllers/share-consent.js';
import { createFeeReadinessController } from './controllers/fee-readiness.js';
import { createLaunchRegistryController } from './controllers/launch-registry.js';
import { createBoostCheckoutController } from './controllers/boost-checkout.js';
import { createTokenCardsController } from './controllers/token-cards.js';
import { createAirdropDirectoryController } from './controllers/airdrop-directory.js';
import { createCommunityClaimsController } from './controllers/community-claims.js';
import { createAirdropReportingController } from './controllers/airdrop-reporting.js';
import { createBuybackController } from './controllers/buyback.js';
import { createFundedTradingController } from './controllers/funded-trading.js';
import { createBuybackPreviewController } from './controllers/buyback-preview.js';
import { createFollowingController } from './controllers/following.js';
import { createExploreFiltersController } from './controllers/explore-filters.js';
import { createAnalyticsController } from './controllers/analytics.js';
import { createLeaderboardsController } from './controllers/leaderboards.js';
import { createHomeFeedController } from './controllers/home-feed.js';
import { createHomeFiltersController } from './controllers/home-filters.js';
import { createExploreLoadingController } from './controllers/explore-loading.js';
import { createExploreRegistryController } from './controllers/explore-registry.js';
import { createTradeStateController } from './controllers/trade-state.js';
import { createTradeExecutionController } from './controllers/trade-execution.js';
import { createWalletSessionController } from './controllers/wallet-session.js';
import { createLaunchPreviewController } from './controllers/launch-preview.js';
import { createLaunchReviewController } from './controllers/launch-review.js';
import { createLaunchFormController } from './controllers/launch-form.js';
import { createWalletMetricsController } from './controllers/wallet-metrics.js';
import { createWalletConnectController } from './controllers/wallet-connect.js';
import { createLaunchNavigationController } from './controllers/launch-navigation.js';
import { createLaunchSubmitController } from './controllers/launch-submit.js';
import { createLaunchActionsController } from './controllers/launch-actions.js';
import { createTradeControlsController } from './controllers/trade-controls.js';
import { createExploreActionsController } from './controllers/explore-actions.js';
import { createNavigationController } from './controllers/navigation.js';
import { createCreatorFeesController } from './controllers/creator-fees.js';
import { createCoinHeaderController } from './controllers/coin-header.js';
import { createPortfolioController } from './controllers/portfolio.js';
import { createCoinMarketController } from './controllers/coin-market.js';
import { createCoinCommunityController } from './controllers/coin-community.js';
import { createCoinStateController } from './controllers/coin-state.js';
import { createCoinLoadingController } from './controllers/coin-loading.js';
import { createCoinNavigationController } from './controllers/coin-navigation.js';
import { createCoinChatController } from './controllers/coin-chat.js';
import { createRewardIdentityController } from './controllers/reward-identity.js';
import { createWalletSignIn } from '../../wallet-signin.js';

export function registerAppControllers(appState) {
  Object.assign(appState, createConnectionsController(appState));
  Object.assign(appState, createLaunchPolicyController(appState));
  Object.assign(appState, createReferralsController(appState));
  Object.assign(appState, createShareConsentController(appState));
  Object.assign(appState, createFeeReadinessController(appState));
  Object.assign(appState, createLaunchRegistryController(appState));
  Object.assign(appState, createBoostCheckoutController(appState));
  Object.assign(appState, createTokenCardsController(appState));
  Object.assign(appState, createAirdropDirectoryController(appState));
  Object.assign(appState, createCommunityClaimsController(appState));
  Object.assign(appState, createAirdropReportingController(appState));
  Object.assign(appState, createBuybackController(appState));
  Object.assign(appState, createFundedTradingController(appState));
  Object.assign(appState, createBuybackPreviewController(appState));
  Object.assign(appState, createFollowingController(appState));
  Object.assign(appState, createExploreFiltersController(appState));
  Object.assign(appState, createAnalyticsController(appState));
  Object.assign(appState, createLeaderboardsController(appState));
  Object.assign(appState, createHomeFeedController(appState));
  Object.assign(appState, createHomeFiltersController(appState));
  Object.assign(appState, createExploreLoadingController(appState));
  Object.assign(appState, createExploreRegistryController(appState));
  Object.assign(appState, createTradeStateController(appState));
  Object.assign(appState, createTradeExecutionController(appState));
  Object.assign(appState, createWalletSessionController(appState));
  Object.assign(appState, createLaunchPreviewController(appState));
  Object.assign(appState, createLaunchReviewController(appState));
  Object.assign(appState, createLaunchFormController(appState));
  Object.assign(appState, createWalletMetricsController(appState));
  Object.assign(appState, createWalletConnectController(appState));
  Object.assign(appState, createLaunchNavigationController(appState));
  Object.assign(appState, createLaunchSubmitController(appState));
  Object.assign(appState, createLaunchActionsController(appState));
  Object.assign(appState, createTradeControlsController(appState));
  Object.assign(appState, createExploreActionsController(appState));
  Object.assign(appState, createNavigationController(appState));
  Object.assign(appState, createCreatorFeesController(appState));
  Object.assign(appState, createCoinHeaderController(appState));
  Object.assign(appState, createPortfolioController(appState));
  Object.assign(appState, createCoinMarketController(appState));
  Object.assign(appState, createCoinCommunityController(appState));
  Object.assign(appState, createCoinStateController(appState));
  Object.assign(appState, createCoinLoadingController(appState));
  Object.assign(appState, createCoinNavigationController(appState));
  Object.assign(appState, createCoinChatController(appState));
  Object.assign(appState, createRewardIdentityController(appState));
  appState.walletSignIn = createWalletSignIn({
    request: appState.apiRequest,
    assertCurrent: session => appState.assertWalletSessionCurrent(session),
    encodeSignature: bytes => appState.bs58.encode(bytes),
  });
}
