import { initializeInitialState } from './startup/initial-state.js';
import { initializeConnections } from './startup/connections.js';
import { initializeLaunchPolicy } from './startup/launch-policy.js';
import { initializeReferrals } from './startup/referrals.js';
import { initializeShareConsent } from './startup/share-consent.js';
import { initializeFeeReadiness } from './startup/fee-readiness.js';
import { initializeLaunchRegistry } from './startup/launch-registry.js';
import { initializeBoostCheckout } from './startup/boost-checkout.js';
import { initializeTokenCards } from './startup/token-cards.js';
import { initializeAirdropDirectory } from './startup/airdrop-directory.js';
import { initializeBuyback } from './startup/buyback.js';
import { initializeBuybackPreview } from './startup/buyback-preview.js';
import { initializeFollowing } from './startup/following.js';
import { initializeExploreFilters } from './startup/explore-filters.js';
import { initializeAnalytics } from './startup/analytics.js';
import { initializeLeaderboards } from './startup/leaderboards.js';
import { initializeHomeFeed } from './startup/home-feed.js';
import { initializeHomeFilters } from './startup/home-filters.js';
import { initializeExploreLoading } from './startup/explore-loading.js';
import { initializeExploreRegistry } from './startup/explore-registry.js';
import { initializeTradeState } from './startup/trade-state.js';
import { initializeTradeExecution } from './startup/trade-execution.js';
import { initializeLaunchPreview } from './startup/launch-preview.js';
import { initializeLaunchReview } from './startup/launch-review.js';
import { initializeWalletConnect } from './startup/wallet-connect.js';
import { initializeLaunchNavigation } from './startup/launch-navigation.js';
import { initializeLaunchActions } from './startup/launch-actions.js';
import { initializeTradeControls } from './startup/trade-controls.js';
import { initializeExploreSearchActions } from './startup/explore-search-actions.js';
import { initializeExploreFiltersActions } from './startup/explore-filters-actions.js';
import { initializeNavigation } from './startup/navigation.js';
import { initializeCreatorFees } from './startup/creator-fees.js';
import { initializeCoinHeader } from './startup/coin-header.js';
import { initializePortfolio } from './startup/portfolio.js';
import { initializeCoinMarket } from './startup/coin-market.js';
import { initializeCoinCommunity } from './startup/coin-community.js';
import { initializeCoinLoading } from './startup/coin-loading.js';
import { initializeCoinNavigation } from './startup/coin-navigation.js';
import { initializeCoinChat } from './startup/coin-chat.js';
import { initializeRewardIdentity } from './startup/reward-identity.js';

// Preserve initialization and listener registration order across feature boundaries.
export async function startApp(appState) {
  initializeInitialState(appState);
  initializeConnections(appState);
  initializeLaunchPolicy(appState);
  initializeReferrals(appState);
  initializeShareConsent(appState);
  initializeFeeReadiness(appState);
  initializeLaunchRegistry(appState);
  initializeBoostCheckout(appState);
  initializeTokenCards(appState);
  initializeAirdropDirectory(appState);
  initializeBuyback(appState);
  initializeBuybackPreview(appState);
  initializeFollowing(appState);
  initializeExploreFilters(appState);
  initializeAnalytics(appState);
  initializeLeaderboards(appState);
  initializeHomeFeed(appState);
  initializeHomeFilters(appState);
  initializeExploreLoading(appState);
  initializeExploreRegistry(appState);
  initializeTradeState(appState);
  initializeTradeExecution(appState);
  initializeLaunchPreview(appState);
  initializeLaunchReview(appState);
  initializeWalletConnect(appState);
  initializeLaunchNavigation(appState);
  initializeLaunchActions(appState);
  initializeTradeControls(appState);
  initializeExploreSearchActions(appState);
  initializeExploreFiltersActions(appState);
  await initializeNavigation(appState);
  initializeCreatorFees(appState);
  initializeCoinHeader(appState);
  initializePortfolio(appState);
  initializeCoinMarket(appState);
  initializeCoinCommunity(appState);
  initializeCoinLoading(appState);
  initializeCoinNavigation(appState);
  initializeCoinChat(appState);
  initializeRewardIdentity(appState);
}
